import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from "@/src/components/ui/Toast";
import { ClientErrorLogger } from "@/components/client-error-logger";

const geistSans = { variable: "" } as const;
const geistMono = { variable: "" } as const;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastProvider>
          <ClientErrorLogger />
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
